# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.22.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.22.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/marinaromanova/cpp-base-hse-2022/projects/image_processor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/marinaromanova/cpp-base-hse-2022/projects/image_processor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.22.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.22.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marinaromanova/cpp-base-hse-2022/projects/image_processor/CMakeFiles /Users/marinaromanova/cpp-base-hse-2022/projects/image_processor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/marinaromanova/cpp-base-hse-2022/projects/image_processor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named image_processor

# Build rule for target.
image_processor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 image_processor
.PHONY : image_processor

# fast build rule for target.
image_processor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/build
.PHONY : image_processor/fast

BMP.o: BMP.cpp.o
.PHONY : BMP.o

# target to build an object file
BMP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/BMP.cpp.o
.PHONY : BMP.cpp.o

BMP.i: BMP.cpp.i
.PHONY : BMP.i

# target to preprocess a source file
BMP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/BMP.cpp.i
.PHONY : BMP.cpp.i

BMP.s: BMP.cpp.s
.PHONY : BMP.s

# target to generate assembly for a file
BMP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/BMP.cpp.s
.PHONY : BMP.cpp.s

Image.o: Image.cpp.o
.PHONY : Image.o

# target to build an object file
Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Image.cpp.o
.PHONY : Image.cpp.o

Image.i: Image.cpp.i
.PHONY : Image.i

# target to preprocess a source file
Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Image.cpp.i
.PHONY : Image.cpp.i

Image.s: Image.cpp.s
.PHONY : Image.s

# target to generate assembly for a file
Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/Image.cpp.s
.PHONY : Image.cpp.s

filters/Crop.o: filters/Crop.cpp.o
.PHONY : filters/Crop.o

# target to build an object file
filters/Crop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Crop.cpp.o
.PHONY : filters/Crop.cpp.o

filters/Crop.i: filters/Crop.cpp.i
.PHONY : filters/Crop.i

# target to preprocess a source file
filters/Crop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Crop.cpp.i
.PHONY : filters/Crop.cpp.i

filters/Crop.s: filters/Crop.cpp.s
.PHONY : filters/Crop.s

# target to generate assembly for a file
filters/Crop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Crop.cpp.s
.PHONY : filters/Crop.cpp.s

filters/Edge_Detection.o: filters/Edge_Detection.cpp.o
.PHONY : filters/Edge_Detection.o

# target to build an object file
filters/Edge_Detection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Edge_Detection.cpp.o
.PHONY : filters/Edge_Detection.cpp.o

filters/Edge_Detection.i: filters/Edge_Detection.cpp.i
.PHONY : filters/Edge_Detection.i

# target to preprocess a source file
filters/Edge_Detection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Edge_Detection.cpp.i
.PHONY : filters/Edge_Detection.cpp.i

filters/Edge_Detection.s: filters/Edge_Detection.cpp.s
.PHONY : filters/Edge_Detection.s

# target to generate assembly for a file
filters/Edge_Detection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Edge_Detection.cpp.s
.PHONY : filters/Edge_Detection.cpp.s

filters/Filter.o: filters/Filter.cpp.o
.PHONY : filters/Filter.o

# target to build an object file
filters/Filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Filter.cpp.o
.PHONY : filters/Filter.cpp.o

filters/Filter.i: filters/Filter.cpp.i
.PHONY : filters/Filter.i

# target to preprocess a source file
filters/Filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Filter.cpp.i
.PHONY : filters/Filter.cpp.i

filters/Filter.s: filters/Filter.cpp.s
.PHONY : filters/Filter.s

# target to generate assembly for a file
filters/Filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Filter.cpp.s
.PHONY : filters/Filter.cpp.s

filters/FilterFactory.o: filters/FilterFactory.cpp.o
.PHONY : filters/FilterFactory.o

# target to build an object file
filters/FilterFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/FilterFactory.cpp.o
.PHONY : filters/FilterFactory.cpp.o

filters/FilterFactory.i: filters/FilterFactory.cpp.i
.PHONY : filters/FilterFactory.i

# target to preprocess a source file
filters/FilterFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/FilterFactory.cpp.i
.PHONY : filters/FilterFactory.cpp.i

filters/FilterFactory.s: filters/FilterFactory.cpp.s
.PHONY : filters/FilterFactory.s

# target to generate assembly for a file
filters/FilterFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/FilterFactory.cpp.s
.PHONY : filters/FilterFactory.cpp.s

filters/GaussianBlur.o: filters/GaussianBlur.cpp.o
.PHONY : filters/GaussianBlur.o

# target to build an object file
filters/GaussianBlur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/GaussianBlur.cpp.o
.PHONY : filters/GaussianBlur.cpp.o

filters/GaussianBlur.i: filters/GaussianBlur.cpp.i
.PHONY : filters/GaussianBlur.i

# target to preprocess a source file
filters/GaussianBlur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/GaussianBlur.cpp.i
.PHONY : filters/GaussianBlur.cpp.i

filters/GaussianBlur.s: filters/GaussianBlur.cpp.s
.PHONY : filters/GaussianBlur.s

# target to generate assembly for a file
filters/GaussianBlur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/GaussianBlur.cpp.s
.PHONY : filters/GaussianBlur.cpp.s

filters/Grayscale.o: filters/Grayscale.cpp.o
.PHONY : filters/Grayscale.o

# target to build an object file
filters/Grayscale.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Grayscale.cpp.o
.PHONY : filters/Grayscale.cpp.o

filters/Grayscale.i: filters/Grayscale.cpp.i
.PHONY : filters/Grayscale.i

# target to preprocess a source file
filters/Grayscale.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Grayscale.cpp.i
.PHONY : filters/Grayscale.cpp.i

filters/Grayscale.s: filters/Grayscale.cpp.s
.PHONY : filters/Grayscale.s

# target to generate assembly for a file
filters/Grayscale.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Grayscale.cpp.s
.PHONY : filters/Grayscale.cpp.s

filters/MatrixFilter.o: filters/MatrixFilter.cpp.o
.PHONY : filters/MatrixFilter.o

# target to build an object file
filters/MatrixFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/MatrixFilter.cpp.o
.PHONY : filters/MatrixFilter.cpp.o

filters/MatrixFilter.i: filters/MatrixFilter.cpp.i
.PHONY : filters/MatrixFilter.i

# target to preprocess a source file
filters/MatrixFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/MatrixFilter.cpp.i
.PHONY : filters/MatrixFilter.cpp.i

filters/MatrixFilter.s: filters/MatrixFilter.cpp.s
.PHONY : filters/MatrixFilter.s

# target to generate assembly for a file
filters/MatrixFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/MatrixFilter.cpp.s
.PHONY : filters/MatrixFilter.cpp.s

filters/Negative.o: filters/Negative.cpp.o
.PHONY : filters/Negative.o

# target to build an object file
filters/Negative.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Negative.cpp.o
.PHONY : filters/Negative.cpp.o

filters/Negative.i: filters/Negative.cpp.i
.PHONY : filters/Negative.i

# target to preprocess a source file
filters/Negative.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Negative.cpp.i
.PHONY : filters/Negative.cpp.i

filters/Negative.s: filters/Negative.cpp.s
.PHONY : filters/Negative.s

# target to generate assembly for a file
filters/Negative.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Negative.cpp.s
.PHONY : filters/Negative.cpp.s

filters/Sharpening.o: filters/Sharpening.cpp.o
.PHONY : filters/Sharpening.o

# target to build an object file
filters/Sharpening.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Sharpening.cpp.o
.PHONY : filters/Sharpening.cpp.o

filters/Sharpening.i: filters/Sharpening.cpp.i
.PHONY : filters/Sharpening.i

# target to preprocess a source file
filters/Sharpening.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Sharpening.cpp.i
.PHONY : filters/Sharpening.cpp.i

filters/Sharpening.s: filters/Sharpening.cpp.s
.PHONY : filters/Sharpening.s

# target to generate assembly for a file
filters/Sharpening.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/filters/Sharpening.cpp.s
.PHONY : filters/Sharpening.cpp.s

image_processor.o: image_processor.cpp.o
.PHONY : image_processor.o

# target to build an object file
image_processor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.cpp.o
.PHONY : image_processor.cpp.o

image_processor.i: image_processor.cpp.i
.PHONY : image_processor.i

# target to preprocess a source file
image_processor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.cpp.i
.PHONY : image_processor.cpp.i

image_processor.s: image_processor.cpp.s
.PHONY : image_processor.s

# target to generate assembly for a file
image_processor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/image_processor.dir/build.make CMakeFiles/image_processor.dir/image_processor.cpp.s
.PHONY : image_processor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... image_processor"
	@echo "... BMP.o"
	@echo "... BMP.i"
	@echo "... BMP.s"
	@echo "... Image.o"
	@echo "... Image.i"
	@echo "... Image.s"
	@echo "... filters/Crop.o"
	@echo "... filters/Crop.i"
	@echo "... filters/Crop.s"
	@echo "... filters/Edge_Detection.o"
	@echo "... filters/Edge_Detection.i"
	@echo "... filters/Edge_Detection.s"
	@echo "... filters/Filter.o"
	@echo "... filters/Filter.i"
	@echo "... filters/Filter.s"
	@echo "... filters/FilterFactory.o"
	@echo "... filters/FilterFactory.i"
	@echo "... filters/FilterFactory.s"
	@echo "... filters/GaussianBlur.o"
	@echo "... filters/GaussianBlur.i"
	@echo "... filters/GaussianBlur.s"
	@echo "... filters/Grayscale.o"
	@echo "... filters/Grayscale.i"
	@echo "... filters/Grayscale.s"
	@echo "... filters/MatrixFilter.o"
	@echo "... filters/MatrixFilter.i"
	@echo "... filters/MatrixFilter.s"
	@echo "... filters/Negative.o"
	@echo "... filters/Negative.i"
	@echo "... filters/Negative.s"
	@echo "... filters/Sharpening.o"
	@echo "... filters/Sharpening.i"
	@echo "... filters/Sharpening.s"
	@echo "... image_processor.o"
	@echo "... image_processor.i"
	@echo "... image_processor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

